// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW2TJeH99kNRWJbyeplcvP5vkwjreM2ZU',
    appId: '1:572995712688:web:8f40acceed975da29f6d75',
    messagingSenderId: '572995712688',
    projectId: 'pwee-9c495',
    authDomain: 'pwee-9c495.firebaseapp.com',
    storageBucket: 'pwee-9c495.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW2TJeH99kNRWJbyeplcvP5vkwjreM2ZU',
    appId: '1:572995712688:android:8f40acceed975da29f6d75',
    messagingSenderId: '572995712688',
    projectId: 'pwee-9c495',
    storageBucket: 'pwee-9c495.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW2TJeH99kNRWJbyeplcvP5vkwjreM2ZU',
    appId: '1:572995712688:ios:8f40acceed975da29f6d75',
    messagingSenderId: '572995712688',
    projectId: 'pwee-9c495',
    storageBucket: 'pwee-9c495.firebasestorage.app',
    iosBundleId: 'com.example.publicwifi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW2TJeH99kNRWJbyeplcvP5vkwjreM2ZU',
    appId: '1:572995712688:macos:8f40acceed975da29f6d75',
    messagingSenderId: '572995712688',
    projectId: 'pwee-9c495',
    storageBucket: 'pwee-9c495.firebasestorage.app',
    iosBundleId: 'com.example.publicwifi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW2TJeH99kNRWJbyeplcvP5vkwjreM2ZU',
    appId: '1:572995712688:windows:8f40acceed975da29f6d75',
    messagingSenderId: '572995712688',
    projectId: 'pwee-9c495',
    authDomain: 'pwee-9c495.firebaseapp.com',
    storageBucket: 'pwee-9c495.firebasestorage.app',
  );
}
